# Generated by Django 5.0.4 on 2026-07-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='serviceinqu_status_e91a3c_idx')],
            },
        ),
    ]
