# Generated by Django 5.0.4 on 2026-07-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='We Build Digital Excellence', max_length=200)),
                ('subheading', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('button_text', models.CharField(blank=True, default='Get Started', max_length=50)),
                ('button_link', models.CharField(blank=True, default='/contact', max_length=200)),
                ('animated_words', models.JSONField(blank=True, default=list, help_text='List of words/phrases to animate/rotate in the hero heading')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(help_text="e.g. '150+', '99%'", max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='hero.hero')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
