# Generated by Django 5.0.4 on 2026-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Quantum Tech Nepal', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('google_map_embed', models.TextField(blank=True, help_text='Google Maps embed URL or iframe src')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Phone number or wa.me link', max_length=30)),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. Sun–Fri: 9:00 AM – 6:00 PM', max_length=255)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
